name: lgbm
model_params:
  objective: binary
  metric: auc
  boosting: gbdt
  max_depth: 7
  num_leaves: 75
  learning_rate: 0.01
  colsample_bytree: 0.7
  subsample: 0.7
  subsample_freq: 1
  seed: 111
  feature_fraction_seed: 111
  drop_seed: 111
  verbose: -1
  n_jobs: -1
  first_metric_only: True

train_params:
  num_boost_round: 50000
  early_stopping_rounds: 200
  verbose_eval: 200
