version: 1
how: group_kfold
callbacks:
  on_split_start:
    - AddColumn:
        column_name: group
  on_split_end:
    - DeleteColumns:
        column_name: group
params:
  random_state: 42
  n_splits: 5
