version: 1

dataset:
  dir: input/
  feature_dir: features/
  params:

output_dir: output/

log_dir: log/

callbacks:

pipeline:
  - lgbm_with_av:
      features:
        - config/features/v1/_basic.yml
      preprocess:
      av: config/adversarial/v1/_av_with_lgbm.yml
      split: config/split/v1/_kfold.yml
      model: config/model/v1/_lgbm_regression.yml
